import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.49.1'
import Stripe from 'https://esm.sh/stripe@17.7.0'
const stripe = new Stripe(Deno.env.get('STRIPE_SECRET_KEY')!, { apiVersion: '2024-12-18.acacia' })
const supabaseAdmin = createClient(Deno.env.get('SUPABASE_URL')!, Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!)
const PP = Deno.env.get('CONNECT_PRICE_ID')||'price_PLACEHOLDER'
const AO=['https://castford.com','https://www.castford.com','https://castford.vercel.app','http://localhost:3000']
function cors(r:Request){const o=r.headers.get('origin')||'';return{'Access-Control-Allow-Origin':AO.includes(o)?o:AO[0],'Access-Control-Allow-Methods':'POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization, apikey'};}
function json(d:any,s=200,h:any={}){return new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json',...h}});}
Deno.serve(async(req:Request)=>{
  const headers=cors(req);if(req.method==='OPTIONS')return new Response('ok',{headers});if(req.method!=='POST')return json({error:'Method not allowed'},405,headers);
  const ah=req.headers.get('Authorization');if(!ah?.startsWith('Bearer '))return json({error:'Missing authorization'},401,headers);
  const token=ah.replace('Bearer ','');const{data:{user},error:authError}=await supabaseAdmin.auth.getUser(token);if(authError||!user)return json({error:'Invalid token'},401,headers);
  const{data:profile}=await supabaseAdmin.from('users').select('org_id, role, full_name, email').eq('id',user.id).maybeSingle();if(!profile?.org_id)return json({error:'No organization'},404,headers);
  try{
    const body=await req.json();const action=body.action;const origin=req.headers.get('origin')||'https://castford.com';
    if(action==='create_account'){const dn=body.display_name||profile.full_name||'My Business';const ce=body.contact_email||user.email||'';const{data:existing}=await supabaseAdmin.from('connected_accounts').select('id,stripe_account_id').eq('org_id',profile.org_id).maybeSingle();if(existing)return json({status:'existing',account_id:existing.stripe_account_id},200,headers);const account=await stripe.accounts.create({type:'custom',country:'US',email:ce,capabilities:{card_payments:{requested:true},transfers:{requested:true}},business_type:'company',business_profile:{name:dn,url:origin,mcc:'5734'},tos_acceptance:{date:Math.floor(Date.now()/1000),ip:req.headers.get('x-forwarded-for')||'127.0.0.1'},metadata:{org_id:profile.org_id,user_id:user.id,platform:'castford'}});await supabaseAdmin.from('connected_accounts').insert({org_id:profile.org_id,user_id:user.id,stripe_account_id:account.id,display_name:dn,contact_email:ce});await supabaseAdmin.from('audit_log').insert({user_id:user.id,org_id:profile.org_id,action:'connect.account_created',resource_type:'stripe_connect',resource_id:account.id}).catch(()=>{});return json({status:'created',account_id:account.id},201,headers);}
    if(action==='simulate_onboarding'){const{data:conn}=await supabaseAdmin.from('connected_accounts').select('stripe_account_id').eq('org_id',profile.org_id).maybeSingle();if(!conn)return json({error:'No connected account'},404,headers);const a=conn.stripe_account_id;await stripe.accounts.update(a,{business_profile:{name:body.business_name||'Castford Test Business',url:'https://castford.com',mcc:'5734',product_description:'Cloud FP&A software'},company:{name:body.business_name||'Castford Test Business',tax_id:'000000000',address:{line1:'123 Main Street',city:'San Francisco',state:'CA',postal_code:'94105',country:'US'},phone:'5555555555'}});const person=await stripe.accounts.createPerson(a,{first_name:'Test',last_name:'Person',email:'test@castford.com',phone:'5555555555',address:{line1:'123 Main Street',city:'San Francisco',state:'CA',postal_code:'94105',country:'US'},dob:{day:1,month:1,year:1990},ssn_last_4:'0000',relationship:{representative:true,executive:true,owner:true,percent_ownership:100,title:'CEO'}});await stripe.accounts.update(a,{company:{owners_provided:true,executives_provided:true}});const bt=await stripe.tokens.create({bank_account:{country:'US',currency:'usd',routing_number:'110000000',account_number:'000123456789',account_holder_name:'Castford Test Business',account_holder_type:'company'}});await stripe.accounts.createExternalAccount(a,{external_account:bt.id});const acct=await stripe.accounts.retrieve(a);const pe=acct.charges_enabled||false;const ds=acct.details_submitted||false;const rem=acct.requirements?.currently_due||[];await supabaseAdmin.from('connected_accounts').update({onboarding_complete:rem.length===0,payments_enabled:pe,details_submitted:ds,capabilities_status:acct.capabilities||{},updated_at:new Date().toISOString()}).eq('stripe_account_id',a);return json({status:'onboarding_simulated',account_id:a,payments_enabled:pe,details_submitted:ds,remaining_requirements:rem},200,headers);}
    if(action==='onboarding_link'){const{data:conn}=await supabaseAdmin.from('connected_accounts').select('stripe_account_id').eq('org_id',profile.org_id).maybeSingle();if(!conn)return json({error:'No connected account'},404,headers);const al=await stripe.accountLinks.create({account:conn.stripe_account_id,refresh_url:`${origin}?connect=refresh`,return_url:`${origin}?connect=return`,type:'account_onboarding'});return json({url:al.url,account_id:conn.stripe_account_id},200,headers);}
    if(action==='status'){const{data:conn}=await supabaseAdmin.from('connected_accounts').select('stripe_account_id, subscription_status').eq('org_id',profile.org_id).maybeSingle();if(!conn)return json({status:'no_account'},200,headers);const acct=await stripe.accounts.retrieve(conn.stripe_account_id);const pe=acct.charges_enabled||false;const ds=acct.details_submitted||false;const oc=ds&&!acct.requirements?.currently_due?.length;await supabaseAdmin.from('connected_accounts').update({onboarding_complete:oc,payments_enabled:pe,details_submitted:ds,capabilities_status:acct.capabilities||{},updated_at:new Date().toISOString()}).eq('stripe_account_id',conn.stripe_account_id);return json({status:'active',account_id:conn.stripe_account_id,payments_enabled:pe,details_submitted:ds,onboarding_complete:oc,requirements:acct.requirements?.currently_due||[],subscription_status:conn.subscription_status},200,headers);}
    if(action==='subscribe'){const{data:conn}=await supabaseAdmin.from('connected_accounts').select('stripe_account_id').eq('org_id',profile.org_id).maybeSingle();if(!conn)return json({error:'No connected account'},404,headers);if(PP==='price_PLACEHOLDER')return json({error:'Set CONNECT_PRICE_ID'},503,headers);const session=await stripe.checkout.sessions.create({mode:'subscription',line_items:[{price:PP,quantity:1}],success_url:`${origin}?connect=subscribed&session_id={CHECKOUT_SESSION_ID}`,cancel_url:`${origin}?connect=cancel`,metadata:{org_id:profile.org_id,connected_account_id:conn.stripe_account_id}});return json({url:session.url,session_id:session.id},200,headers);}
    if(action==='billing_portal'){const{data:org}=await supabaseAdmin.from('organizations').select('stripe_customer_id').eq('id',profile.org_id).maybeSingle();if(!org?.stripe_customer_id)return json({error:'No billing customer'},404,headers);const ps=await stripe.billingPortal.sessions.create({customer:org.stripe_customer_id,return_url:`${origin}?view=settings`});return json({url:ps.url},200,headers);}
    if(action==='create_product'){const{data:conn}=await supabaseAdmin.from('connected_accounts').select('stripe_account_id').eq('org_id',profile.org_id).maybeSingle();if(!conn)return json({error:'No connected account'},404,headers);const product=await stripe.products.create({name:body.name||'New Product',description:body.description||'',default_price_data:{unit_amount:body.price_cents||1000,currency:body.currency||'usd'}},{stripeAccount:conn.stripe_account_id});return json({product_id:product.id,name:product.name},201,headers);}
    if(action==='list_products'){if(!body.account_id)return json({error:'account_id required'},400,headers);const products=await stripe.products.list({limit:20,active:true,expand:['data.default_price']},{stripeAccount:body.account_id});return json({products:products.data.map(p=>({id:p.id,name:p.name,price:(p.default_price as any)?.unit_amount,currency:(p.default_price as any)?.currency,price_id:(p.default_price as any)?.id}))},200,headers);}
    if(action==='checkout'){if(!body.account_id||!body.price_data)return json({error:'account_id and price_data required'},400,headers);const session=await stripe.checkout.sessions.create({line_items:[{price_data:{currency:body.price_data.currency||'usd',unit_amount:body.price_data.unit_amount,product_data:{name:body.price_data.product_name||'Purchase'}},quantity:body.quantity||1}],mode:'payment',success_url:`${origin}/success?session_id={CHECKOUT_SESSION_ID}`,cancel_url:`${origin}/cancel`},{stripeAccount:body.account_id});return json({url:session.url,session_id:session.id},200,headers);}
    return json({error:`Unknown action: ${action}`},400,headers);
  }catch(err:any){return json({error:err?.message||'Internal error'},500,headers);}
});
